server {
    listen 8080;
	server_name localhost;
    host 127.0.0.1;
    root docs/fusion_web;
    client_max_body_size 3000000;
	index index.html;
    error_page 404 error_pages/404.html;

    location image {
        root www;
        allow_methods  DELETE POST GET;
        index hhh.html;
        autoindex on;
        return www.youtube.com;
    }
    location image/hhh {
        root www;
        allow_methods  DELETE POST GET;
        index hhh.html;
        autoindex on;
        return www.youtube.com;
    }
    cgi_conf .sh /bin/sh;
    cgi_conf .php /bin/php;
}
